name: dir-creation
on: push
jobs:
  dir-creation-job:
    runs-on: ubuntu-latest
    steps:
      - name: create-dir
        run: mkdir tests
      - name: write-text
        run: cd tests
      - run: touch test.txt
      - run: echo "This is a test!" >> test.txt
